"""Curated original chapter prose, versioned separately from identity and literature facts.

Shared gene claims come from gene_companion_content; figures from the figure source.
Changing this source requires regeneration, editorial-seal refresh and publication gates.
"""
EDITORIAL_VERSION = "UNIFIED_GUIDE_V1"
CANONICAL = "06_RESOURCES/Genomics/BREAST_CANCER_60_GENE_COMPANION.md"
LABEL = "Breast Cancer Research Guide — People, Data, Biology and 60 Genes"
CHAPTERS = [('The People Behind the Numbers',
  'A diagnosis changes daily life: appointments, uncertainty, relationships, employment and care '
  'all matter. Research begins with that human purpose. Molecular tables offer a limited view of a '
  "specimen; they do not summarize a person's experience or determine their future. We use "
  'population estimates to understand the scale of the need, while respecting the people '
  'represented by each observation.\n'
  '\n'
  'The **2024 global estimates** distinguish three different quantities:\n'
  '\n'
  '| Measure | Estimate | Population and meaning |\n'
  '|---|---:|---|\n'
  '| Annual incidence | 2,434,087 | Women; new breast cancer diagnoses during 2024 |\n'
  '| Annual mortality | 693,660 | Women; deaths attributed to breast cancer during 2024 |\n'
  '| Five-year prevalence | 8,162,335 | Both sexes; people alive in 2024 diagnosed within '
  'approximately the preceding five years |\n'
  '\n'
  'These are modeled estimates, not a live participant registry. Annual deaths are not deaths '
  "among exactly that year's newly diagnosed people. Five-year prevalence excludes survivors "
  'diagnosed longer ago; **total survivors cannot be inferred from it**. The incidence/mortality '
  'population differs from the prevalence population. Sources accessed 10 October 2026: [IARC '
  'incidence](https://gco.iarc.who.int/today/en/dataviz/tables?cancers=20&mode=population&sexes=2&types=0), '
  '[IARC '
  'mortality](https://gco.iarc.who.int/today/en/dataviz/tables?cancers=20&mode=population&sexes=2&types=1), '
  '[IARC '
  'prevalence](https://gco.iarc.who.int/today/en/dataviz/tables-prevalence?cancers=20&mode=population&types=2) '
  'and [2024 global statistics '
  'paper](https://acsjournals.onlinelibrary.wiley.com/doi/10.3322/caac.70090).\n'
  '\n'
  'Access to timely diagnosis and treatment varies across communities. A molecular research cohort '
  'cannot by itself explain those differences or represent everyone affected. [WHO breast cancer '
  'overview](https://www.who.int/news-room/fact-sheets/detail/breast-cancer) supplies '
  'public-health context. Better biological explanations must ultimately be evaluated alongside '
  'access, outcomes and the priorities of people receiving care. To understand what one study can '
  'contribute, we first need to understand how its dataset was assembled.'),
 ('Understanding the Breast Cancer Dataset',
  '**The Cancer Genome Atlas (TCGA)** characterized tumors using several molecular technologies. '
  '**TCGA-BRCA** names its breast invasive carcinoma project. This resource lets researchers '
  'compare measurements across tumors and ask how molecular differences relate to a defined '
  'question. It is a research collection, not a population survey. The [GDC project '
  'API](https://api.gdc.cancer.gov/projects/TCGA-BRCA?expand=summary) snapshot accessed **10 '
  'October 2026** reported **1,098 cases**. That project-level figure is neither a complete-pair '
  'count nor the size of a separate study subset; holdings can change. [NCI guidance on '
  'TCGA](https://www.cancer.gov/ccg/research/genome-sequencing/tcga/using-tcga-data).\n'
  '\n'
  'Follow the chain of observation units before counting:\n'
  '\n'
  '| Unit | Meaning in a research workflow |\n'
  '|---|---|\n'
  '| Patient / participant | The person contributing material under the applicable consent |\n'
  "| Case | A project record representing a participant; verify the project's mapping |\n"
  '| Specimen | Tissue obtained at a particular collection event or location |\n'
  '| Sample | Material selected or processed for an assay; terminology depends on the archive |\n'
  '| Sequencing library | Prepared molecules submitted to sequencing; several can derive from one '
  'specimen |\n'
  '| Data file | Stored output from an assay or processing step; many files can describe one '
  'sample |\n'
  '\n'
  'Do not count files as independent people. A matched comparison requires verified links between '
  'the two specimens and their participant, with a defined rule for duplicates. Tumor-adjacent '
  'normal tissue and tissue from a separate unaffected donor are different controls. “Normal” '
  'describes a sampling definition; it does not guarantee identical composition, exposure or '
  'molecular state.\n'
  '\n'
  'Ethical collection, consent and controlled access govern permissible uses. Public documentation '
  'or summary metadata does not authorize unrestricted release of sensitive records. A '
  'reproducible analysis records source version, inclusion rules, identity linkage and processing '
  'choices without publishing identifiers. This guide contains no participant-level TCGA data. '
  'Once the observational units are clear, the next question is what the assay actually measures.'),
 ('How Researchers Measure Genes',
  '### Start learning\n'
  '\n'
  '**DNA** stores sequence information. **Transcription** produces RNA from selected DNA regions; '
  '**translation** uses protein-coding RNA to make proteins. Some RNAs, including MALAT1, function '
  'without encoding a protein. **Gene expression** describes production or abundance in a '
  'specified context. It does not mean that every step from DNA to biological activity changes '
  'together.\n'
  '\n'
  'RNA sequencing samples fragments derived from RNA. A **raw count** records assigned sequencing '
  'evidence under a defined pipeline; it depends on sequencing depth, assignment rules and the '
  'tissue mixture. **Normalization** makes a specified comparison more interpretable by addressing '
  'technical scale or composition. It does not remove all confounding. TPM and other normalized '
  'quantities are not raw counts and must not be substituted for them in a count model.\n'
  '\n'
  '{{FIGURE_1}}\n'
  '\n'
  '### A worked measurement example\n'
  '\n'
  'Invent two comparable normalized measurements: 20 units in a simulated tumor preparation and 10 '
  'in its simulated comparator. Their ratio is 2, and **log2 fold change** is log2(20/10) = +1. '
  'Reversing the comparison yields −1. A value of +2 would describe a fourfold ratio, not two '
  'additional molecules. These chosen numbers have no sampling uncertainty, significance or '
  'biological discovery attached. Zero denominators require a prospectively specified method; '
  'adding a constant changes the estimand and must be disclosed.\n'
  '\n'
  'A **variant** changes DNA sequence; **copy number** concerns genomic dosage. Neither is '
  'established by high RNA. Total protein, protein localization and activation-related assays '
  'answer further questions. Clinical ER, PR and HER2 results use defined pathology methods and '
  'criteria; a transcript value is not the corresponding clinical result. [NCI biomarker '
  'testing](https://www.cancer.gov/types/breast/diagnosis/breast-cancer-biomarker-tests).\n'
  '\n'
  '### Working glossary\n'
  '\n'
  '- **Abundance:** how much of a specified molecule is measured, on a stated scale.\n'
  '- **Activation:** a functional state assessed through an appropriate activity-related '
  'measurement.\n'
  '- **Bulk tissue:** an assay combining molecular contributions from multiple cells.\n'
  '- **Contrast:** a specified comparison, including its numerator, denominator and units.\n'
  '- **Confounding:** a factor associated with the comparison and outcome that can distort '
  'interpretation.\n'
  '- **Perturbation:** a deliberate intervention used to investigate a biological response.\n'
  '- **Calibration:** checking whether a statistical procedure behaves as promised under relevant '
  'conditions.\n'
  '\n'
  'Use this [glossary](#working-glossary) when reading the gene profiles; a [focused measurement '
  'reference](GENE_EXPRESSION_INTERPRETATION.md#glossary) provides additional terms. Having '
  'separated measurements, we can now examine why tumors do not share one molecular pattern.'),
 ('Why Tumors Behave Differently',
  'Breast tumors can share an anatomical diagnosis while differing in differentiation, '
  'proliferation and signaling. **Molecular heterogeneity** means those differences are '
  'biologically structured rather than one universal expression pattern. Multi-gene classifiers '
  'summarize selected patterns; they do not capture every feature of every cell.\n'
  '\n'
  '**Luminal A** emphasizes luminal differentiation and hormone-associated expression themes. '
  '**Luminal B** retains luminal themes but differs in proliferation and other aspects of its '
  'expression program. **HER2-enriched** describes an expression-defined group with HER-family '
  'signaling themes. **Basal-like** describes basal-associated expression patterns. These '
  'plain-language themes introduce the categories; they are not a decision rule based on one '
  'marker. [Parker classifier study](https://pubmed.ncbi.nlm.nih.gov/19204204/) and [TCGA '
  'multi-platform study](https://pubmed.ncbi.nlm.nih.gov/23000897/) are primary readings, reviewed '
  'here at abstract level.\n'
  '\n'
  '{{FIGURE_4}}\n'
  '\n'
  '**PAM50** uses a defined multi-gene expression method. Clinical ER, PR and HER2 categories use '
  'separate tissue assays. HER2-enriched and HER2-positive overlap incompletely; basal-like and '
  'triple-negative also differ. This 60-gene teaching catalog is neither PAM50 nor a validated '
  'diagnostic classifier.\n'
  '\n'
  'A bulk specimen includes epithelial, immune and stromal cells. Higher CD8A can reflect more '
  'contributing T cells, higher expression within them, or both. Higher COL1A1 can reflect stromal '
  'content rather than a tumor-cell program. Cell-resolved and spatial methods help distinguish '
  'source populations and location. The [tumor atlas](https://pubmed.ncbi.nlm.nih.gov/34493872/) '
  'and [normal breast atlas](https://pubmed.ncbi.nlm.nih.gov/38548988/) provide study-specific '
  'context; their specimen definitions are not interchangeable. The following biological systems '
  'connect these cell and measurement distinctions to the gene atlas.'),
 ('The Biology Behind the 60 Genes',
  'Cells maintain identity, respond to signals, divide, repair damage and interact with '
  'neighboring cells. The ten connected lessons below follow those tasks. Their gene links point '
  'to profiles within this guide. Shared processes can motivate an experiment; they do not '
  'establish direct molecular interactions in a particular tumor.\n'
  '\n'
  '{{BIOLOGY}}\n'
  '\n'
  '{{FIGURE_2}}\n'
  '\n'
  'These processes overlap: a stress response can affect transcription, while tissue composition '
  'changes apparent immune or matrix abundance. The original **12 teaching domains** remain '
  'available in the [structured domain index](GENE_ATLAS_INDEX.md#by-biological-domain). They are '
  'organizational categories, not mutually exclusive pathways. We next examine individual genes '
  'using the same distinction between normal function, study findings and measurement limits.'),
 ('The Integrated 60-Gene Atlas',
  '### Explore the catalog\n'
  '\n'
  'This atlas retains **21 foundational genes and 39 additions**, with exactly 60 HGNC-approved '
  "identities. It is a public teaching selection, not the private project's frozen signature, a "
  'prognostic score or a validated clinical assay. The [selection '
  'rubric](REFERENCES/SELECTION_RUBRIC.md) explains the teaching rationale.\n'
  '\n'
  'Each profile derives its function, study finding and specific limitation from the same curated '
  'catalog as its complete card. Annotation was cross-checked against HGNC, NCBI Gene and Ensembl '
  'on **2026-10-10**. That identity state is `ANNOTATION_VERIFIED`. Literature review remains '
  '**`ABSTRACT_ONLY`**: bibliographic records and abstracts were reviewed, but full methods, '
  'supplements and results were not independently audited. The primary-paper link beside each '
  'account identifies its evidence; the full card records design, model, identifiers and further '
  'caveats. A randomized trial context does not turn a gene transcript into a clinical selection '
  'test.\n'
  '\n'
  '### Alphabetical gene lookup\n'
  '\n'
  'Choose a symbol to jump to its integrated profile. Profiles are grouped by biological topic, '
  'with one entry per gene even when several domain memberships apply.\n'
  '\n'
  '{{ATLAS}}\n'
  '\n'
  'Use the gene-specific measurement limit to formulate the next question. The shared [measurement '
  'glossary](#working-glossary) covers abundance, activation and perturbation; the next chapter '
  'explains how individual genes can be studied together.'),
 ('From Genes to Biological Pathways',
  'A **pathway** organizes biological processes or reactions; a gene set identifies members under '
  'a documented definition. Curated resources such as '
  '[Reactome](https://reactome.org/userguide/analysis) connect identifiers to annotated processes. '
  'Record the database version, species, identifier mapping and tested background before comparing '
  'studies. A pathway label is useful only when its membership and evidence are specified.\n'
  '\n'
  '{{FIGURE_3}}\n'
  '\n'
  '**Coexpression** means measurements vary together. A common cell population, shared regulator '
  'or batch effect can produce that pattern. A **causal interaction** requires evidence that '
  'changing one component affects another under appropriate controls. Binding, regulation and '
  'shared category membership are distinct claims. For example, FOXA1 and ESR1 can share a '
  'hormone-related teaching category while their regulatory relationship requires chromatin and '
  'perturbation evidence in a particular model.\n'
  '\n'
  'Gene-set analysis asks whether a prespecified group shows a pattern beyond a suitable '
  'background. Results depend on the measurement universe, overlapping sets, dependencies among '
  'genes and multiple testing. Selecting a few attractive genes after seeing a plot and calling '
  'them an enriched pathway ignores that selection process. A pathway score from bulk RNA also '
  'inherits cell-mixture ambiguity. The [focused pathway reference](GENE_PATHWAY_OVERVIEW.md) '
  'lists useful connections and the assays needed to test them. Moving from a plausible biological '
  'connection to a supported finding requires an explicit research workflow.'),
 ('From Measurements to Scientific Evidence',
  'Begin with a question whose population, measurement and comparison are explicit. Then follow '
  'this sequence:\n'
  '\n'
  '**Research question → cohort selection → specimen identity → measurement → quality control → '
  'comparison → statistical analysis → visualization → interpretation → validation.**\n'
  '\n'
  'Cohort rules determine who is represented. Identity checks establish which observations belong '
  'together. Quality control examines assay integrity, missingness, depth and unexpected structure '
  'before models are chosen. Keep exclusions auditable; do not remove inconvenient observations '
  'solely because they weaken a preferred result.\n'
  '\n'
  '{{FIGURE_5}}\n'
  '\n'
  'In an invented design, 10 complete pairs comprise 10 independent people and 20 specimens, not '
  '20 independent people. A within-person contrast can control stable person-level differences. It '
  'does not remove tissue-composition differences, collection effects or systematic assay '
  'differences. A patient-blocked model must represent the pair structure; ignoring it changes the '
  'uncertainty calculation.\n'
  '\n'
  '**Confounding** can arise when sequencing batch or collection setting aligns with the '
  'biological group. If every tumor was processed in one batch and every comparator in another, '
  'the data cannot separately identify those effects without additional design information. '
  'Plotting helps diagnose a problem; it does not repair the design.\n'
  '\n'
  'Testing many genes gives many chances for a chance finding. A p-value concerns a specified null '
  'model; it is not the probability a biological hypothesis is true. **False discovery rate '
  '(FDR)** describes an expected proportion of false discoveries among a selected set under the '
  "procedure's assumptions, not a probability attached to each individual gene. Report effect "
  "size, uncertainty, testing family and adjustment method together. [Benjamini and Hochberg's "
  'original procedure](https://doi.org/10.1111/j.2517-6161.1995.tb02031.x) supplies the '
  'methodological reference.\n'
  '\n'
  'Predefine contrasts and validation targets where possible. Internal resampling evaluates '
  'behavior within available data; an independent cohort tests transport to new observations. '
  'Neither a small adjusted p-value nor a compelling heatmap establishes mechanism or clinical '
  'usefulness. The next chapter teaches how to read the visual summary without asking it to answer '
  'questions outside its inputs.'),
 ('Reading the Scientific Figures',
  'Read the title, observation unit, axes, scale and legend before interpreting a color or '
  'cluster. Ask what values were supplied, what transformations were applied and what uncertainty '
  'is displayed. The process diagrams in earlier chapters have no numerical units: their arrows '
  'express conceptual steps or categories, as described in each caption.\n'
  '\n'
  '{{FIGURE_6}}\n'
  '\n'
  'In the synthetic heatmap, TeachA changes from +2 in C1 to −1 in C4. Those labels specify '
  'fourfold and one-half ratios under the stated comparison. A row z-score would answer a '
  "different question about deviations from that row's mean; it would not retain these ratio "
  'units. The unchanged numerical range across columns allows direct scale comparison. None of '
  'these chosen values supports a subtype, cluster, p-value or actual gene result.\n'
  '\n'
  'For a scatterplot, check whether one dot is a specimen, person or aggregate. For a boxplot, '
  'inspect sample sizes and whether repeated observations violate a simple independent-group '
  'interpretation. For a model plot, determine whether intervals describe means, predictions or '
  'another quantity. Color and ordering can guide attention but cannot substitute for those '
  'definitions. The [plot-reading guide](../READING_PLOTS.md) and [visualization '
  'gallery](../VISUALIZATION_GALLERY.md) extend these skills. We now gather the remaining '
  'inferential limits before working through a complete example.'),
 ('What the Data Cannot Tell Us',
  '### Read evidence with its limits\n'
  '\n'
  '**Sampling and selection:** a surgical collection may underrepresent people without access to '
  'those institutions or those whose disease was not sampled. A result can be internally '
  'consistent yet poorly representative. Document recruitment, exclusions, missingness and '
  'population coverage before extending a claim.\n'
  '\n'
  '**Composition and assay:** an RNA association in mixed tissue cannot locate the producing cell. '
  'Sequence variants, transcript abundance, protein staining and functional assays measure '
  'different things. Cross-platform agreement is evidence to investigate, while disagreement can '
  'reveal measurement or biological context rather than a simple error.\n'
  '\n'
  '**Observation and causality:** an association may arise from common causes or reverse '
  'relationships. Controlled perturbation can test a specific effect in a model, but its '
  "applicability depends on dose, timing, controls and model choice. MALAT1's contrasting "
  'experiments illustrate why context matters; PTEN illustrates why RNA and protein findings need '
  'not agree.\n'
  '\n'
  '{{FIGURE_7}}\n'
  '\n'
  '**Statistical and clinical importance:** a precisely estimated small expression difference may '
  'have little practical consequence. A large exploratory difference may be unstable. Clinical '
  'usefulness requires an appropriate endpoint, validation population and decision context beyond '
  'a molecular association.\n'
  '\n'
  '**Validation and prognosis:** reusing the same cohort for discovery and evaluation can give '
  'optimistic performance. Internal validation and independent external validation answer '
  'different questions. A molecular classification groups expression patterns; it does not '
  "determine an individual's prognosis. A prognostic association is also distinct from evidence "
  'that a marker predicts benefit from a particular treatment.\n'
  '\n'
  'To distinguish a finding from a hypothesis, write what was actually observed, in which units '
  'and population, then state the alternative explanations. Propose the additional design or assay '
  'needed to discriminate them. The synthetic walkthrough applies that discipline from the first '
  'question to the final sentence.'),
 ('Working Through a Research Question',
  '**Question:** in six invented complete pairs, does a teaching measurement tend to be higher in '
  'a simulated tumor preparation than its matched comparator? The unit of inference is an invented '
  'pair. The labels and measurements are chosen for arithmetic practice, not sampled patients, '
  'sequencing counts or real genes.\n'
  '\n'
  '| Invented pair | Comparator units | Tumor units | log2(tumor/comparator) |\n'
  '|---|---:|---:|---:|\n'
  '| DemoPair1 | 10 | 20 | +1 |\n'
  '| DemoPair2 | 10 | 40 | +2 |\n'
  '| DemoPair3 | 10 | 10 | 0 |\n'
  '| DemoPair4 | 10 | 5 | −1 |\n'
  '| DemoPair5 | 10 | 20 | +1 |\n'
  '| DemoPair6 | 10 | 10 | 0 |\n'
  '\n'
  '**Inspect:** all six pair links are complete, denominators are positive and the comparison '
  'direction is fixed. These are already comparable fictional units; fitting an RNA count model to '
  'this table would be inappropriate. In an actual dataset, normalization, quality and identity '
  'would require independent evidence.\n'
  '\n'
  '**Plot:** a paired-line plot would connect the two measurements within each pair; a contrast '
  'plot would show six log2 values with a zero line. Five values are nonnegative but only three '
  'are positive. A mean alone hides the negative contrast and the two unchanged pairs. The '
  '[paired-line helper](../R/README.md) and [gallery](../VISUALIZATION_GALLERY.md) provide '
  'plotting patterns; keep these observation units when adapting them.\n'
  '\n'
  '**Evaluate uncertainty:** the arithmetic mean is 0.5 log2 units, with contrasts from −1 to +2. '
  'Omitting one pair at a time gives means from 0.2 to 0.8. This is sensitivity to one '
  'observation, **not a confidence interval**, a p-value or evidence about a population. Because '
  'the values were deliberately chosen, no sampling claim follows. A real uncertainty analysis '
  'would require a sampling model, sufficient independent observations, appropriate pair handling '
  'and calibration.\n'
  '\n'
  '**Write the conclusion:** “In this six-pair invented table, the mean log2 ratio was 0.5, with '
  'mixed directions and leave-one-pair means of 0.2–0.8. The example demonstrates paired '
  'arithmetic and sensitivity; it does not establish a cancer mechanism, population effect or '
  'clinical decision.”\n'
  '\n'
  'Reproduce these calculations with [the original R '
  'walkthrough](FIGURES/gene_companion_walkthrough.R). It accepts no private inputs and writes no '
  'outputs. After checking arithmetic, study [statistical '
  'reasoning](#chapter-8-from-measurements-to-scientific-evidence) and the [research '
  'limitations](#chapter-10-what-the-data-cannot-tell-us) before replacing fictional values with '
  'authorized research data.'),
 ('Research Practice, References and Next Steps',
  'You should now be able to distinguish a person from a specimen and file, explain an RNA '
  'measurement, compare molecular and clinical classifications, navigate 60 gene functions, and '
  'separate a supported observation from a mechanistic or clinical hypothesis.\n'
  '\n'
  'Before interpreting a result, ask:\n'
  '\n'
  '1. What question, population and observation unit were specified?\n'
  '2. Which source, specimen linkage, assay and transformation produced the values?\n'
  '3. Does the comparison respect pairing, confounding and the testing family?\n'
  '4. What effect and uncertainty are reported, and how was the procedure calibrated?\n'
  '5. What does the design support, what alternatives remain, and what independent evidence is '
  'needed?\n'
  '\n'
  '**Beginner exercise:** explain the 20/10 example without using the word “significant”; identify '
  'why the person and the two specimens are different units. Then run the synthetic walkthrough.\n'
  '\n'
  '**Intermediate exercise:** compare ESR1, CD8A and COL1A1. Specify a producing-cell hypothesis, '
  "an assay that addresses it, and a bulk-RNA alternative explanation. Use each card's source and "
  'measurement limit.\n'
  '\n'
  '**Advanced exercise:** compare the opposing MALAT1 studies or PTEN RNA/protein context. '
  'Tabulate intervention, model, endpoint and review extent. Propose a prospective analysis with '
  'defined inclusion rules, contrasts, multiplicity control and independent validation; do not '
  'present an unperformed experiment as evidence.\n'
  '\n'
  'The [annotation register](REFERENCES/ANNOTATION_SOURCE_REGISTER.md), [literature evidence '
  'matrix](REFERENCES/GENE_EVIDENCE_MATRIX.md) and [selection '
  'rubric](REFERENCES/SELECTION_RUBRIC.md) retain identity, evidence state and selection scope. '
  'All literature accounts in this edition remain `ABSTRACT_ONLY`; no deeper audit or replication '
  'is claimed. Continue with [R resources](../R/README.md), [follow-along '
  'computing](../../FOLLOW_ALONG.md), [research planning](../../01_Capstone/README.md) and '
  '[literature methods](../Literature/README.md). Record versions, assumptions and reproducible '
  'scripts before interpreting real measurements.\n'
  '\n'
  '### Reproduce and validate\n'
  '\n'
  'From the repository root, run the read-only consistency checks and synthetic tests:\n'
  '\n'
  '```bash\n'
  'python3 scripts/build_gene_companion.py --check\n'
  'python3 scripts/validate_gene_companion.py\n'
  'python3 -m unittest discover -s tests -v\n'
  'python3 06_RESOURCES/Presentation/check_navigation.py\n'
  'Rscript --vanilla 06_RESOURCES/tests/test_gene_companion_heatmap.R\n'
  'Rscript --vanilla 06_RESOURCES/tests/test_gene_companion_walkthrough.R\n'
  '```\n'
  '\n'
  'The [curated catalog](../../scripts/gene_companion_content.py), [chapter '
  'source](../../scripts/gene_companion_chapters.py), [shared '
  'figures](../../scripts/gene_companion_figures.py) and '
  '[builder](../../scripts/build_gene_companion.py) reproduce the reading and reference views. '
  'Offline consistency does not constitute fresh annotation or deeper literature verification.\n'
  '\n'
  'This is an educational guide, not clinical advice, a diagnostic assay or a validated research '
  'signature. Its limits are part of the scientific lesson. Careful definitions and reproducible '
  'analysis help researchers ask better questions, while the purpose remains better understanding '
  'and evidence that can eventually serve patients and public health.')]

BIOLOGY_LESSONS = [('Cellular identity and differentiation',
  'KRT8 KRT18 KRT5 KRT14 KRT17 GATA3',
  'Cell identity is maintained through coordinated structural and regulatory programs. '
  'Luminal-associated and basal-associated keratins help describe epithelial states. A specimen '
  'containing several cell states can express both sets; one keratin does not assign a tumor '
  'subtype. Differentiation establishes the context in which incoming signals are interpreted.'),
 ('Hormone and growth-factor signaling',
  'ESR1 PGR FOXA1 ERBB2 PIK3CA AKT1 MTOR',
  'Hormone receptors link ligand and chromatin context to transcription. Membrane growth receptors '
  'communicate through intracellular signaling systems. Receptor abundance, receptor partners and '
  'protein activation are distinct measurements. Equal receptor RNA in two cultures can coexist '
  'with different responses after a controlled ligand exposure. Signals can influence the '
  'cell-cycle machinery discussed next.'),
 ('Cell proliferation and checkpoints',
  'MKI67 CCND1 CCNE1 CDK4 CDK6 RB1 CDKN1A',
  'Cyclins and kinases coordinate progression through the cell cycle; checkpoint systems constrain '
  'that progression. MKI67 is associated with cycling cells. More cycling-cell marker RNA can '
  'reflect a greater fraction of cycling cells rather than faster division by each cell. DNA '
  'synthesis labeling and microscopy address complementary questions about proliferation.'),
 ('DNA damage and repair',
  'ATM CHEK2 BRCA1 BRCA2 PALB2 RAD51 BARD1',
  'Damage responses detect disruption and organize repair. Homologous-recombination machinery '
  'helps preserve sequence information during division. An abundant transcript can encode a '
  'defective protein when a damaging variant is present. Sequence interpretation and a suitable '
  'functional assay are needed to evaluate that possibility; unchanged RNA cannot exclude an '
  'inherited variant.'),
 ('Cell survival and death',
  'TP53 PTEN BCL2 BAX',
  'Checkpoint signaling, growth brakes and regulated cell death affect whether a stressed cell '
  'survives. BCL2 and BAX contribute to opposing survival processes, while TP53 and PTEN address '
  'different control systems. Exposure, timing and protein state matter. A survival phenotype is '
  'an endpoint to test rather than a direct reading of one transcript.'),
 ('Tissue architecture and adhesion',
  'CDH1 EPCAM ITGA6 KRT19',
  'Junctions and matrix attachment organize cells into tissues. Lower bulk CDH1 can result from '
  'fewer epithelial cells even when remaining cells retain junctions. Protein localization and '
  'histology help distinguish tissue composition from altered adhesion. Architecture provides the '
  'setting for interactions with extracellular material.'),
 ('Invasion and extracellular matrix',
  'COL1A1 FN1 MMP9 VIM CXCL12',
  'Collagen and fibronectin help form the extracellular framework; remodeling enzymes and cell '
  'states can alter that environment. Fibroblasts and other stromal cells contribute important '
  'signals. More matrix RNA does not identify its producing cell or prove invasion. MMP9 abundance '
  'does not establish activated proteolysis; localization and activity assays address the specific '
  'claim.'),
 ('Immune microenvironment',
  'CD3D CD8A CD68 PTPRC PDCD1 CD274 STAT1',
  'Immune populations communicate and respond within the tissue. Lineage-associated transcripts '
  'can reflect numbers of contributing cells, while checkpoint transcripts can come from different '
  'compartments. A CD8A increase does not by itself demonstrate effective killing. Spatial '
  'identity, activation and functional endpoints are needed to distinguish recruitment from '
  'effective response.'),
 ('Metabolism and cellular stress',
  'SLC2A1 HIF1A XBP1',
  'Nutrient uptake, oxygen responses and protein-folding stress influence cellular adaptation. '
  'Transporter RNA does not measure glucose flux. Protein stability can regulate HIF1A, and XBP1 '
  'splicing can change while total RNA remains similar. Direct metabolic, protein or isoform '
  'measurements complement gene-level abundance.'),
 ('Transcriptional regulation and emerging mechanisms',
  'GATA3 FOXA1 FOXC1 STAT1 MALAT1',
  'Transcription factors act within chromatin and cofactor contexts; correlated transcripts do not '
  'prove a regulatory edge. Noncoding RNA adds mechanisms that need not involve translation. '
  'MALAT1 has opposing findings across perturbation models and disease contexts. Compare rescue, '
  'neighboring-gene effects, host context and endpoint before assigning one universal direction.')]
