"""Original conceptual diagrams and literal synthetic matrix; shared presentation source."""
FIGURE_SOURCE_VERSION = "UNIFIED_FIGURES_V1"
FIGURE_INTRO = "# Seven visual explanations\n\n[Companion](../BREAST_CANCER_60_GENE_COMPANION.md) · [Measurement guide](../GENE_EXPRESSION_INTERPRETATION.md) · [Gallery](../../VISUALIZATION_GALLERY.md)\n\nThese original Mermaid diagrams render directly on GitHub. Every schematic is **conceptual**, with no patient values or dataset inputs. Text labels carry meaning independently of color. Category accents follow the repository's Okabe–Ito blue and green; signed numerical values use its blue–neutral–red diverging palette. Source links identify biological or methodological concepts, not reused artwork. If a viewer cannot render Mermaid, the captions and heatmap table retain the explanation."

FIGURES = [('DNA to protein',
  '```mermaid\n'
  'flowchart TD\n'
  '  D["DNA sequence and copy number"] -->|transcription| R["RNA production and abundance"]\n'
  '  R -->|translation for coding transcripts| P["Protein abundance"]\n'
  '  P --> A["Activity: regulation, location and partners"]\n'
  '  R --> N["Noncoding RNA: RNA-mediated functions"]\n'
  '  classDef concept fill:#FFFFFF,stroke:#0072B2,color:#111111,stroke-width:2px;\n'
  '  class D,R,P,A,N concept;\n'
  '```\n'
  '\n'
  '**Figure 1 caption.** Conceptual relationship among sequence, transcription, translation and '
  'function; arrows describe processes, not measured correlations. RNA stability and protein '
  'turnover also affect abundance. Noncoding transcripts such as MALAT1 do not follow a '
  'protein-coding translation route. **Inputs:** independently drawn process schematic; no '
  'numerical units. **Sources:** the public NCBI functional records on '
  '[ESR1](../GENE_CARDS/ESR1.md) and [MALAT1](../GENE_CARDS/MALAT1.md); [multi-platform TCGA '
  'study](https://pubmed.ncbi.nlm.nih.gov/23000897/).\n'
  '\n'
  '**Text equivalent:** DNA is transcribed into RNA. Coding RNA can be translated into protein, '
  'whose activity depends on regulation, location and partners. Noncoding RNA has a separate '
  'RNA-function branch.'),
 ('Epithelial signaling',
  '```mermaid\n'
  'flowchart TD\n'
  '  H["Hormone context"] --> E["ESR1 / PGR receptor response"]\n'
  '  C["FOXA1 and chromatin accessibility"] --> E\n'
  '  E --> T["Transcriptional response"]\n'
  '  G["Growth-factor context"] --> HER["HER-family receptors"]\n'
  '  HER --> S["PI3K / AKT / mTOR signaling"]\n'
  '  S --> B["Growth and nutrient responses"]\n'
  '  classDef concept fill:#FFFFFF,stroke:#0072B2,color:#111111,stroke-width:2px;\n'
  '  class H,E,C,T,G,HER,S,B concept;\n'
  '```\n'
  '\n'
  '**Figure 2 caption.** Conceptual, simplified epithelial signaling framework. These are '
  'process-level links, not a complete wiring diagram or evidence that every receptor signals '
  'identically in every tumor. Ligand, receptor partners, protein activation and cell context '
  'matter. **Inputs:** original schematic from the [hormone and growth '
  'lessons](../GENE_BIOLOGY_LEARNING_GUIDE.md); no numerical units. **Sources:** [FOXA1 functional '
  'study](https://pubmed.ncbi.nlm.nih.gov/21151129/) and the NCBI records on '
  '[ERBB2](../GENE_CARDS/ERBB2.md), [PIK3CA](../GENE_CARDS/PIK3CA.md), '
  '[AKT1](../GENE_CARDS/AKT1.md) and [MTOR](../GENE_CARDS/MTOR.md).\n'
  '\n'
  '**Text equivalent:** Hormone context and FOXA1/chromatin context feed receptor response and '
  'transcription. A separate growth-factor branch connects HER-family receptors to PI3K/AKT/mTOR '
  'and growth/nutrient responses; this is a process framework.'),
 ('Category network',
  '```mermaid\n'
  'flowchart TD\n'
  '  E["ESR1, PGR"] --- H["Hormone signaling"]\n'
  '  F["FOXA1"] --- H\n'
  '  F --- T["Transcriptional regulation"]\n'
  '  B["BRCA1, BRCA2, RAD51"] --- R["DNA repair"]\n'
  '  K["KRT5, KRT14, KRT17"] --- I["Epithelial identity"]\n'
  '  C["CD3D, CD8A, PTPRC"] --- M["Immune microenvironment"]\n'
  '  classDef category fill:#FFFFFF,stroke:#009E73,color:#111111,stroke-width:2px;\n'
  '  class H,T,R,I,M category;\n'
  '```\n'
  '\n'
  '**Figure 3 caption.** Conceptual gene-to-category teaching network. An undirected line means '
  '**category membership**, not direct binding or a molecular interaction. FOXA1 illustrates '
  'multiple domain membership. **Inputs:** independently selected categories in the '
  '[rubric](../REFERENCES/SELECTION_RUBRIC.md) and [domain index](../GENE_ATLAS_INDEX.md); no '
  'numerical units. **Sources:** linked card annotation records and [FOXA1 primary '
  'reading](https://pubmed.ncbi.nlm.nih.gov/21151129/).\n'
  '\n'
  '**Text equivalent:** ESR1/PGR connect to the hormone category; FOXA1 connects to hormone and '
  'transcription categories. Repair, epithelial identity and immune categories group their labeled '
  'genes. Lines denote membership only.'),
 ('Molecular subtype overview',
  '```mermaid\n'
  'flowchart TD\n'
  '  M["Specified multi-gene expression classification"] --> A["Luminal A: luminal / '
  'hormone-related themes"]\n'
  '  M --> B["Luminal B: luminal themes with distinct proliferation context"]\n'
  '  M --> H["HER2-enriched: HER-family signaling themes"]\n'
  '  M --> K["Basal-like: basal-associated expression themes"]\n'
  '  C["Clinical ER / PR / HER2 tissue assays"] -. "incomplete overlap; separate definitions" .-> '
  'M\n'
  '  classDef concept fill:#FFFFFF,stroke:#0072B2,color:#111111,stroke-width:2px;\n'
  '  class M,A,B,H,K,C concept;\n'
  '```\n'
  '\n'
  '**Figure 4 caption.** Conceptual biological themes, not a single-gene decision tree or an '
  'exhaustive classification algorithm. HER2-enriched is not identical to clinical HER2-positive; '
  'basal-like is not identical to triple-negative. Neither RNA from this catalog nor a theme '
  "assigns a person's subtype. **Inputs:** original overview of classifier and multi-platform "
  'study concepts; no numerical units. **Sources:** [Parker classifier '
  'development](https://pubmed.ncbi.nlm.nih.gov/19204204/) and '
  '[TCGA](https://pubmed.ncbi.nlm.nih.gov/23000897/); review extent is recorded in the [evidence '
  'matrix](../REFERENCES/GENE_EVIDENCE_MATRIX.md).\n'
  '\n'
  '**Text equivalent:** A specified multi-gene classification connects to four expression themes. '
  'A dashed line marks incomplete overlap with separate clinical ER/PR/HER2 assays.'),
 ('Paired specimens',
  '```mermaid\n'
  'flowchart TD\n'
  '  P["One conceptual participant; no invented clinical history"] --> T["Tumor specimen: mixed '
  'cell populations"]\n'
  '  P --> N["Adjacent-normal specimen: different mixture"]\n'
  '  T --> A["Bulk RNA assay"]\n'
  '  N --> B["Bulk RNA assay"]\n'
  '  A --> C["Within-pair contrast; direction and units specified"]\n'
  '  B --> C\n'
  '  C --> Q["Cell abundance, cell state or both?"]\n'
  '  classDef concept fill:#FFFFFF,stroke:#0072B2,color:#111111,stroke-width:2px;\n'
  '  class P,T,N,A,B,C,Q concept;\n'
  '```\n'
  '\n'
  '**Figure 5 caption.** Conceptual paired sampling distinguishes one participant from two '
  'specimens and multiple assay files. Pairing does not equate tissue composition or make '
  'adjacent-normal tissue an unaffected-donor control. **Inputs:** invented sampling structure '
  'with no measured values; no numerical units. **Sources:** [measurement '
  'guide](../GENE_EXPRESSION_INTERPRETATION.md), [tumor single-cell '
  'atlas](https://pubmed.ncbi.nlm.nih.gov/34493872/) and [normal breast '
  'atlas](https://pubmed.ncbi.nlm.nih.gov/38548988/).\n'
  '\n'
  '**Text equivalent:** One conceptual participant contributes two tissue specimens. Each '
  'undergoes a bulk RNA assay; the within-pair contrast raises a question about cell abundance, '
  'cell state or both.'),
 ('Synthetic expression heatmap',
  '**Rows:** six invented teaching labels (TeachA–TeachF), not actual gene identities. '
  '**Columns:** four simulated tumor-minus-adjacent-normal comparisons (C1–C4), not patient '
  'identifiers. **Units:** signed log2 fold change; fixed range −2 to +2, zero-centered. These are '
  'chosen demonstration values, with no fitted model, uncertainty or p-values.\n'
  '\n'
  '```mermaid\n'
  '%%{init: {"flowchart": {"rankSpacing": 16, "nodeSpacing": 16, "padding": 6}}}%%\n'
  'flowchart LR\n'
  '  subgraph C1["C1 simulated contrast"]\n'
  '    direction TB\n'
  '    C1A["TeachA: +2"] ~~~ C1B["TeachB: +1"] ~~~ C1C["TeachC: 0"] ~~~ C1D["TeachD: -1"] ~~~ '
  'C1E["TeachE: -2"] ~~~ C1F["TeachF: 0"]\n'
  '  end\n'
  '  subgraph C2["C2 simulated contrast"]\n'
  '    direction TB\n'
  '    C2A["TeachA: +1"] ~~~ C2B["TeachB: 0"] ~~~ C2C["TeachC: -1"] ~~~ C2D["TeachD: -2"] ~~~ '
  'C2E["TeachE: 0"] ~~~ C2F["TeachF: +2"]\n'
  '  end\n'
  '  subgraph C3["C3 simulated contrast"]\n'
  '    direction TB\n'
  '    C3A["TeachA: 0"] ~~~ C3B["TeachB: -1"] ~~~ C3C["TeachC: -2"] ~~~ C3D["TeachD: 0"] ~~~ '
  'C3E["TeachE: +2"] ~~~ C3F["TeachF: +1"]\n'
  '  end\n'
  '  subgraph C4["C4 simulated contrast"]\n'
  '    direction TB\n'
  '    C4A["TeachA: -1"] ~~~ C4B["TeachB: -2"] ~~~ C4C["TeachC: 0"] ~~~ C4D["TeachD: +2"] ~~~ '
  'C4E["TeachE: +1"] ~~~ C4F["TeachF: 0"]\n'
  '  end\n'
  '  C1 ~~~ C2 ~~~ C3 ~~~ C4\n'
  '  classDef neg2 fill:#2166AC,stroke:#333333,color:#FFFFFF;\n'
  '  classDef neg1 fill:#8CAED2,stroke:#333333,color:#111111;\n'
  '  classDef zero fill:#F7F7F7,stroke:#333333,color:#111111;\n'
  '  classDef pos1 fill:#D58F98,stroke:#333333,color:#111111;\n'
  '  classDef pos2 fill:#B2182B,stroke:#333333,color:#FFFFFF;\n'
  '  class C1E,C2D,C3C,C4B neg2;\n'
  '  class C1D,C2C,C3B,C4A neg1;\n'
  '  class C1C,C1F,C2B,C2E,C3A,C3D,C4C,C4F zero;\n'
  '  class C1B,C2A,C3F,C4E pos1;\n'
  '  class C1A,C2F,C3E,C4D pos2;\n'
  '```\n'
  '\n'
  '**Zero-centered legend:** dark blue −2 (one-quarter); lighter blue −1 (one-half); neutral 0 '
  '(equal); lighter red +1 (twofold); dark red +2 (fourfold). Ratios refer to the stated numerator '
  'and denominator. The numeric labels provide a color-independent reading.\n'
  '\n'
  '| Invented row label | C1 | C2 | C3 | C4 |\n'
  '|---|---:|---:|---:|---:|\n'
  '| TeachA | +2 | +1 | 0 | −1 |\n'
  '| TeachB | +1 | 0 | −1 | −2 |\n'
  '| TeachC | 0 | −1 | −2 | 0 |\n'
  '| TeachD | −1 | −2 | 0 | +2 |\n'
  '| TeachE | −2 | 0 | +2 | +1 |\n'
  '| TeachF | 0 | +2 | +1 | 0 |\n'
  '\n'
  '**Figure 6 caption.** Synthetic signed-expression demonstration with deliberately invented '
  'labels and values. This is **log2 fold change, not row z-score**. No clustering or subtype '
  'interpretation is warranted. **Inputs:** the literal invented matrix in [original R '
  'source](gene_companion_heatmap.R); PNG/PDF output is optional and restricted to a directory '
  'outside Git. The R contract verifies the numerical diagram labels against that matrix. '
  "**Sources:** the repository's [scientific palette](../../R/hse_scientific_palette.R), "
  'independently authored fold-change arithmetic and [measurement '
  'explanation](../GENE_EXPRESSION_INTERPRETATION.md).\n'
  '\n'
  '**Text equivalent:** The six-row numerical table above reproduces every diagram value. On '
  "narrow screens, use that table or GitHub's diagram zoom controls; color is never the only "
  'carrier of the value.'),
 ('Interpreting evidence',
  '```mermaid\n'
  'flowchart TD\n'
  '  Q["Which question does the study answer?"] --> C["Correlation: measured variables covary"]\n'
  '  Q --> F["Functional evidence: controlled perturbation changes an endpoint"]\n'
  '  Q --> P["Prognostic association: marker relates to subsequent outcome"]\n'
  '  Q --> V["Clinical validation: a defined test or intervention supports a patient decision"]\n'
  '  C --> L["Check design, controls, confounding, replication and applicability"]\n'
  '  F --> L\n'
  '  P --> L\n'
  '  V --> L\n'
  '  classDef concept fill:#FFFFFF,stroke:#0072B2,color:#111111,stroke-width:2px;\n'
  '  class Q,C,F,P,V,L concept;\n'
  '```\n'
  '\n'
  '**Figure 7 caption.** Conceptual comparison of evidence questions; branches are not an '
  'automatic ladder to clinical use. A controlled experiment can establish an effect in its model '
  'without validating a patient test, and prognosis is not necessarily treatment prediction. '
  '**Inputs:** original evidence taxonomy; no numerical units. **Sources:** [MALAT1 conflicting '
  'model readings](../GENE_CARDS/MALAT1.md), [AKT trial context](../GENE_CARDS/AKT1.md), [evidence '
  'matrix](../REFERENCES/GENE_EVIDENCE_MATRIX.md) and [NCI '
  'assays](https://www.cancer.gov/types/breast/diagnosis/breast-cancer-biomarker-tests).\n'
  '\n'
  '**Text equivalent:** A study question branches into correlation, functional evidence, prognosis '
  'or clinical validation. Every branch requires scrutiny of design, controls, confounding, '
  'replication and applicability.')]
