"""Original biological teaching sequences and invented examples; no patient data."""
DOMAINS = {
 'hormone': ('Hormone signaling',
 'Hormones coordinate tissue responses by binding receptors and changing transcription. ESR1 and PGR encode receptors; FOXA1 helps determine which chromatin regions a receptor can access.',
 'A tumor may retain hormone-responsive differentiation while acquiring additional growth or resistance mechanisms. Receptor presence does not guarantee every downstream response.',
 'Imagine two invented epithelial cultures with equal ESR1 RNA but different receptor binding after hormone exposure. Binding and transcription assays distinguish a functional response from receptor abundance.',
 'Would equal receptor RNA imply equal receptor activity? What information does a pathology protein assay add?',
 'No: ligand, chromatin, variants and other regulators matter. Protein testing adds a different measurement with its own validated interpretation.'),
 'growth': ('Growth-factor signaling',
 'Membrane receptors transmit information about the environment through intracellular enzymes. HER-family receptors and PI3K/AKT/mTOR signaling help coordinate growth and nutrient responses.',
 'Amplification, activating variants, inhibitory-protein loss or altered partners can change signaling. These alternatives cannot be identified from one RNA value.',
 'Imagine equal ERBB2 transcript abundance in two cultures, but increased phosphorylated receptor in one. Compare total protein with phosphoprotein after a controlled ligand pulse.',
 'Which measurement addresses abundance, and which addresses activation? Does a shared pathway imply a direct physical interaction?',
 'Total protein addresses abundance; phosphorylation provides activation-related information in context. Pathway membership alone is not a binding experiment.'),
 'proliferation': ('Proliferation',
 'Cells duplicate DNA and separate chromosomes through ordered cell-cycle phases. Cyclins, kinases and mitotic regulators control timing; MKI67 is associated with cycling cells.',
 'A tissue can have more cycling cells or a different distribution of cell-cycle stages. Both change bulk proliferation-associated RNA without identifying a single initiating defect.',
 'Invent a sample containing 10 cycling cells among 100 and another containing 30 among 100. Higher cycling-cell marker RNA could arise without any change within a cycling cell.',
 'Does a threefold marker increase prove each cell divides three times faster? How could microscopy help?',
 'No. Cell counts, labeling and stage-specific assays help separate cell fraction from cell behavior.'),
 'repair': ('DNA repair',
 'Cells detect damage and repair DNA to preserve information across divisions. ATM and CHEK2 participate in damage responses; BRCA1, BRCA2, PALB2 and RAD51 contribute to homologous-recombination biology.',
 'A pathogenic variant or impaired protein regulation can alter repair. A transcript can remain abundant while the encoded protein is defective.',
 'Imagine a repair gene with unchanged RNA but a damaging DNA variant. Sequence analysis addresses the variant; a suitable functional assay addresses repair performance.',
 'Can RNA exclude a germline variant? Is a variant of uncertain significance equivalent to a pathogenic variant?',
 'No to both. Inherited-variant classification requires dedicated evidence and interpretation; tumor RNA is a different assay.'),
 'suppression': ('Tumor suppression',
 'Checkpoints, signaling brakes and controlled cell death restrain inappropriate expansion. TP53, RB1 and PTEN affect different control systems; BAX and BCL2 influence survival decisions.',
 'Control can fail through DNA changes, protein loss or altered regulation. A stress-induced checkpoint transcript can also accompany cell survival rather than permanent arrest.',
 'Imagine high CDKN1A RNA after oxidative injury. Follow recovery, protein abundance and cell-cycle state before concluding that growth stopped irreversibly.',
 'Does expression of a suppressor prove its protein works? Can a survival phenotype depend on exposure and timing?',
 'Expression does not prove function. Exposure, timing and cell state can change the interpretation of the same gene.'),
 'basal': ('Basal epithelial biology',
 'Epithelial layers use keratin networks and differentiation programs to maintain structure. Basal-associated and luminal-associated keratins describe cell states rather than exclusive identities.',
 'Tumors and experimental epithelial cultures can mix differentiation states. Basal-like is a molecular expression classification; basal cells are a tissue compartment.',
 'Imagine a spatial spot containing basal cells beside luminal tumor cells. KRT5 and KRT8 signals can coexist because the measurement combines cells.',
 'Does KRT5 alone assign basal-like disease? Is basal-like identical to triple-negative?',
 'No. Multi-gene classification and clinical protein categories overlap incompletely, and spatial composition adds another source of variation.'),
 'adhesion': ('Cell adhesion',
 'Cells attach to neighboring cells and extracellular surroundings to organize tissues. CDH1 supports epithelial junctions, EPCAM participates in epithelial organization and ITGA6 contributes to matrix attachment.',
 'Altered adhesion can change architecture or migration, but expression differences can also reflect the number of epithelial cells sampled.',
 'Imagine lower CDH1 RNA in a sample with fewer epithelial cells but intact junctions in the remaining cells. Compare cell localization and protein staining before inferring junction loss.',
 'Does low bulk RNA diagnose lobular histology? What does membrane localization add?',
 'No. Histopathology and localization address tissue architecture and functional placement that an RNA total cannot resolve.'),
 'matrix': ('Invasion and extracellular matrix',
 'Collagen, fibronectin and remodeling enzymes help tissues maintain and reshape their surroundings. Fibroblasts and other stromal cells contribute much of this extracellular framework.',
 'Matrix remodeling can accompany invasion, wound repair or changing stromal content. MMP9 protein must be appropriately activated to act as an enzyme.',
 'Imagine equal collagen production per fibroblast but twice as many fibroblasts in one specimen. Bulk COL1A1 RNA increases without a per-cell regulatory change.',
 'Can collagen RNA identify the producing cell? Does MMP9 RNA establish active proteolysis?',
 'No. Spatial or cell-resolved assays help identify sources; protein processing and activity assays address proteolysis.'),
 'immune': ('Immune microenvironment',
 'Immune cells recognize signals, communicate through cytokines and regulate responses. CD3D, CD8A, CD68 and PTPRC help characterize immune populations; PDCD1 and CD274 participate in checkpoint biology.',
 'A tumor can change immune-cell abundance, location or state. A bulk checkpoint signal may come from immune cells, tumor cells or both.',
 'Imagine increased CD8A RNA with unchanged RNA per T cell. More T cells alone could explain the result; their location and functional state still require measurement.',
 'Does a marker prove effective killing? Does PDCD1 RNA establish eligibility for a checkpoint drug?',
 'No. Marker abundance, functional evidence and clinically validated selection criteria address different questions.'),
 'metabolism': ('Metabolism and stress',
 'Cells regulate nutrient uptake, energy use and responses to low oxygen or protein-folding stress. SLC2A1 transports glucose; HIF1A and XBP1 connect stress sensing to transcription.',
 'Cancer cells may adapt to environmental stress, but nonmalignant cells in the same tissue also respond. Protein stability and RNA splicing can change activity without a corresponding gene-level RNA change.',
 'Imagine unchanged total XBP1 RNA with a changed fraction of the spliced transcript. An isoform assay reveals a difference hidden by the gene total.',
 'Does transporter RNA measure glucose flux? Does HIF1A RNA directly measure oxygen tension?',
 'No. Flux, oxygen measurements, protein regulation and isoforms provide complementary information.'),
 'transcription': ('Transcriptional regulation',
 'Transcription factors and chromatin context coordinate when genes are read. GATA3, FOXA1, FOXC1, STAT1 and stress-responsive regulators influence different programs.',
 'A regulatory network may change through binding, accessibility or cofactors. Correlated RNA values are a useful hypothesis but do not demonstrate a direct regulatory edge.',
 'Imagine FOXA1 and ESR1 RNA rising together. Perturb one regulator and measure binding plus transcription to distinguish shared cell identity from direct dependence.',
 'Does correlation prove binding? What controls would strengthen a perturbation experiment?',
 'No. Appropriate controls, dose, timing, rescue and orthogonal binding assays help distinguish direct and indirect effects.'),
 'emerging': ('Other emerging biology',
 'Noncoding transcripts and context-dependent regulators can affect cellular organization without encoding a protein. MALAT1 is a long noncoding RNA with model-dependent research findings.',
 'Different interventions, neighboring-gene effects and disease stages can produce apparently contradictory outcomes. A useful teaching catalog keeps disagreement visible.',
 'Compare the 2016, 2018 and 2024 MALAT1 studies. Make separate columns for intervention, model, metastatic stage and direction of effect before drawing a conclusion.',
 'Must one contrary study be wrong? Would more RNA alone reveal the mechanism?',
 'Neither follows. Contradictions can reflect design differences, and mechanism requires evidence beyond abundance.')
}
